ePunkt.Portal/Models/Shared/PersonalInformationViewModel.cs
using ePunkt.Api.Responses;
using JetBrains.Annotations;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;

namespace ePunkt.Portal.Models.Shared
{
    public class PersonalInformationViewModel
    {
        public virtual PersonalInformationViewModel Prepare(MandatorResponse mandatorResponse)
        {
            return Prepare(mandatorResponse, null);
        }

        public virtual PersonalInformationViewModel Prepare([NotNull]MandatorResponse mandatorResponse, [CanBeNull] ApplicantResponse applicantResponse)
        {
            AllowEmptyGender = mandatorResponse.PortalSettings.AllowEmptyGender;
            AvailableTitlesBeforeName = from x in mandatorResponse.TitlesBeforeName
                                        select new SelectListItem
                                            {
                                                Value = x.Name,
                                                Text = x.Name
                                            };
            AvailableTitlesAfterName = from x in mandatorResponse.TitlesAfterName
                                       select new SelectListItem
                                           {
                                               Value = x.Name,
                                               Text = x.Name
                                           };
            AvailableCountries = from x in mandatorResponse.Countries
                                 select new SelectListItem
                                     {
                                         Value = x,
                                         Text = x
                                     };
            AvailableNationalities = from x in mandatorResponse.Countries
                                     select new SelectListItem
                                         {
                                             Value = x,
                                             Text = x
                                         };

            if (applicantResponse != null)
                AutoMapper.Mapper.DynamicMap(applicantResponse, this);

            return this;
        }


        public bool? Gender { get; set; }
        public string TitleBeforeName { get; set; }
        public string TitleAfterName { get; set; }
        [Required(ErrorMessage = @"Error-FirstName")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = @"Error-LastName")]
        public string LastName { get; set; }
        [Required(ErrorMessage = @"Error-Email")]
        [DataType(DataType.EmailAddress, ErrorMessage = @"Error-Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = @"Error-Phone")]
        public string Phone { get; set; }
        [Required(ErrorMessage = @"Error-Street")]
        public string Street { get; set; }
        [Required(ErrorMessage = @"Error-ZipCode")]
        public string ZipCode { get; set; }
        [Required(ErrorMessage = @"Error-City")]
        public string City { get; set; }
        [Required(ErrorMessage = @"Error-Country")]
        public string Country { get; set; }
        [Required(ErrorMessage = @"Error-Nationality")]
        public string Nationality { get; set; }
        [Required(ErrorMessage = @"Error-BirthDate")]
        public DateTime BirthDate { get; set; }

        public IEnumerable<SelectListItem> AvailableTitlesBeforeName { get; set; }
        public IEnumerable<SelectListItem> AvailableTitlesAfterName { get; set; }
        public IEnumerable<SelectListItem> AvailableCountries { get; set; }
        public IEnumerable<SelectListItem> AvailableNationalities { get; set; }

        public bool AllowEmptyGender { get; set; }
    }
}

ePunkt.Portal/Controllers/ApplicantController.cs
using ePunkt.Api.Client;
using ePunkt.Api.Client.Requests;
using ePunkt.Portal.Models.Applicant;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ePunkt.Portal.Controllers
{
    [Authorize]
    public class ApplicantController : ControllerBase
    {
        public ApplicantController(ApiHttpClient apiClient, CustomSettings settings)
            : base(apiClient, settings)
        {
        }

        public async Task<ActionResult> Index()
        {
            var applicant = await GetApplicant();
            if (applicant == null)
                return RedirectToAction("Logoff", "Account");

            var documents = await new ApplicantDocumentsGetRequest(applicant.Id).LoadResult(ApiClient);
            var jobProfiles = await new ApplicantJobProfilesGetRequest(applicant.Id).LoadResult(ApiClient);
            var activities = await new ApplicantActivitiesGetRequest(applicant.Id).LoadResult(ApiClient);
            return View(new IndexViewModel(applicant, documents, jobProfiles, activities));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(bool? active, bool? newsletter, bool? matchingJobs)
        {
            var applicant = await GetApplicant();
            if (applicant != null)
            {
                if (active.HasValue)
                    applicant.IsActive = active.Value;
                if (newsletter.HasValue)
                    applicant.EnableNewsletter = newsletter.Value;
                if (matchingJobs.HasValue)
                    applicant.EnableMatchingJobsAutoMail = matchingJobs.Value;
                await new ApplicantPostRequest(applicant.Id, applicant).LoadResult(ApiClient);
            }

            return RedirectToAction("Index");
        }
    }
}

ePunkt.Portal/Controllers/ApplicationsController.cs
using ePunkt.Api.Client;
using ePunkt.Api.Client.Requests;
using ePunkt.Portal.Models.Applications;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ePunkt.Portal.Controllers
{
    [Authorize]
    public class ApplicationsController : ControllerBase
    {
        private readonly LoadJobsService _loadJobsService;

        public ApplicationsController(ApiHttpClient apiClient, CustomSettings settings, LoadJobsService loadJobsService)
            : base(apiClient, settings)
        {
            _loadJobsService = loadJobsService;
        }

        public async Task<ActionResult> Index()
        {
            var mandator = await GetMandator();
            var applications = (await new ApplicationsRequest(GetApplicantId()).LoadResult(ApiClient)).Where(x => x.IsVisibleToApplicant).ToList();
            var viewModel = await new IndexViewModel(applications).Build(mandator, _loadJobsService, Request.Url);
            return View(viewModel);
        }
    }
}

ePunkt.Portal/Controllers/JobsController.cs
using ePunkt.Api.Client;
using ePunkt.Api.Client.Requests;
using ePunkt.Api.Responses;
using ePunkt.Portal.Models.Jobs;
using ePunkt.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace ePunkt.Portal.Controllers
{
    public class JobsController : ControllerBase
    {
        private readonly LoadJobsService _jobsService;

        public JobsController(ApiHttpClient apiClient, CustomSettings settings, LoadJobsService jobsService)
            : base(apiClient, settings)
        {
            _jobsService = jobsService;
        }

        public async Task<ActionResult> Index(string filter, string jobProfiles, string regions)
        {
            var mandator = await GetMandator();
            var response = await _jobsService.LoadJobsForCurrentPortal(Request.Url, mandator);
            var jobs = response.Jobs.Filter(filter, jobProfiles, regions);

            var jobProfilesFilter = (jobProfiles ?? "").Split('|').Select(x => x.Trim()).Where(x => x.HasValue()).ToArray();
            var regionsFilter = (regions ?? "").Split('|').Select(x => x.Trim()).Where(x => x.HasValue()).ToArray();

            var model = new IndexViewModel
                {
                    AvailableJobProfiles = mandator.JobProfiles,
                    AvailableRegions = mandator.Regions,
                    TotalJobsCount = response.Jobs.Count(),
                    FilteredText = filter,
                    FilteredJobProfiles = jobProfilesFilter,
                    FilteredRegions = regionsFilter,
                    DisplayFilter = mandator.PortalSettings.EnableFilterOnJobsList,
                    DisplayJobProfileFilter = mandator.PortalSettings.EnableJobProfilesFilterOnJobsList,
                    DisplayRegionFilter = mandator.PortalSettings.EnableRegionsFilterOnJobsList,
                    DisplayJobDate = mandator.PortalSettings.DisplayDateInJobListing,
                    DisplayJobLocation = mandator.PortalSettings.DisplayLocationInJobListing,
                    MoveFilterToBottom = mandator.PortalSettings.MoveJobsFilterToBottomOnJobsList
                };
            model.BuildJobs(jobs.OrderByDescending(x => x.OnlineDateCorrected));

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Index(string filter)
        {
            var mandator = await GetMandator();

            var selectedRegions = BuildSelectedRegionsString(mandator.Regions);
            selectedRegions = selectedRegions.Trim('|');

            var selectedJobProfiles = mandator.JobProfiles
                .Where(jobProfile => Request.Form[jobProfile].Is(true))
                .Aggregate("", (current, jobProfile) => current + (jobProfile + "|"));
            selectedJobProfiles = selectedJobProfiles.Trim('|');

            return RedirectToAction("Index",
                                    new { filter, jobProfiles = selectedJobProfiles.HasValue() ? selectedJobProfiles : null, regions = selectedRegions.HasValue() ? selectedRegions : null });
        }

        private string BuildSelectedRegionsString(IEnumerable<RegionResponse> regions)
        {
            var selectedRegions = "";
            foreach (var region in regions)
            {
                if (Request.Form[region.Name].Is(true))
                    selectedRegions += region.Name + "|";
                selectedRegions += BuildSelectedRegionsString(region.Regions);
            }
            return selectedRegions;
        }

        public async Task<ActionResult> Job(int id)
        {
            var mandator = await GetMandator();
            var job = await GetJob(mandator, _jobsService, id);
            if (job == null)
                return RedirectToAction("Index");

            var fixUrlsService = new FixJobAdUrlsService(mandator);
            var model = new JobViewModel
                {
                    Html = fixUrlsService.ReplaceUrlsWithCurrent(job.Html, Request.Url),
                    DisplayBackLink = mandator.PortalSettings.DisplayBackToOverviewLinkOnJobDetails
                };
            return View(model);
        }

        //cache it, but only for a very short duration, because otherwise the preview in eR would always load an old version
        [OutputCache(Duration = 30, VaryByParam = "id", Location = OutputCacheLocation.Server)]
        public async Task<ActionResult> SalaryImage(int id)
        {
            try
            {
                var response = await new JobSalaryImageRequest(id).LoadResult(ApiClient);
                if (response != null && response.Image != null)
                    return new FileContentResult(Convert.FromBase64String(response.Image), MimeMapping.GetMimeMapping("JobSalaryImage" + id + ".jpg"));
            }
            // ReSharper disable EmptyGeneralCatchClause
            catch (Exception)
            // ReSharper restore EmptyGeneralCatchClause
            {
                //do nothing here
            }
            throw new HttpException(404, "Job Salary Image not available.");
        }
    }
}

ePunkt.Portal/Views/Shared/Header.cshtml
@using (Html.SwitchLocSource("~/Views/Shared/Header.cshtml"))
{
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse">
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink(@Html.Loc("Profile_Link").ToString(), "Index", "Applicant")</li>
                        <li>@Html.ActionLink(@Html.Loc("Applications_Link").ToString(), "Index", "Applications")</li>
                        <li>@Html.ActionLink(@Html.Loc("Jobs_Link").ToString(), "Index", "Jobs")</li>
                    </ul>

                    <ul class="nav navbar-nav pull-right">

                        <li>@Html.ActionLink(@Html.Loc("ChangePassword_Link").ToString(), "ChangePassword", "Account")</li>
                        <li>@Html.ActionLink(@Html.Loc("ThirdPartyProfiles_Link").ToString(), "Index", "ThirdPartyProfile")</li>
                        <li>@Html.ActionLink(@Html.Loc("Logoff_Link").ToString(), "Logoff", "Account")</li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink(@Html.Loc("Jobs_Link").ToString(), "Index", "Jobs")</li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink(@Html.Loc("Login_Link").ToString(), "Login", "Account")</li>
                    </ul>
                }

            </div>
        </div>
    </div>
}

ePunkt.Portal/Views/Shared/PersonalInformation.cshtml
@model ePunkt.Portal.Models.Shared.PersonalInformationViewModel

<div class="personalInformationPartial">
    @using (Html.SwitchLocSource("~/Views/Shared/PersonalInformation.cshtml"))
    {
        <text>
        @{
        var genders = new List<SelectListItem>
            {
                new SelectListItem {Text = Html.Loc("Mrs.").ToString(), Value = "False"},
                new SelectListItem {Text = Html.Loc("Mr.").ToString(), Value = "True"}
            };
        if (Model.AllowEmptyGender)
        {
            genders.Insert(0, new SelectListItem { Text = Html.Loc("EmptySelection").ToString(), Value = "" });
        }

        var titlesBeforeName = Model.AvailableTitlesBeforeName.ToList();
        titlesBeforeName.Insert(0, new SelectListItem { Text = Html.Loc("EmptySelection").ToString(), Value = "" });
        var titlesAfterName = Model.AvailableTitlesAfterName.ToList();
        titlesAfterName.Insert(0, new SelectListItem { Text = Html.Loc("EmptySelection").ToString(), Value = "" });
        var countries = Model.AvailableCountries.ToList();
        countries.Insert(0, new SelectListItem { Text = Html.Loc("EmptySelection").ToString(), Value = "" });
        var nationalities = Model.AvailableNationalities.ToList();
        nationalities.Insert(0, new SelectListItem { Text = Html.Loc("EmptySelection").ToString(), Value = "" });
        }

        <div class="form-group">
            @Html.LabelFor(x => x.Gender, Html.Loc("Gender").ToString(), new { @class = "control-label" })
            @Html.DropDownListFor(x => x.Gender, genders, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.TitleBeforeName, Html.Loc("Titles").ToString(), new { @class = "control-label" })
            @Html.DropDownListFor(x => x.TitleBeforeName, titlesBeforeName, new { @class = "form-control" }) @Html.DropDownListFor(x => x.TitleAfterName, titlesAfterName, new { @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.FirstName, Html.Loc("FirstName").ToString(), new { @class = "control-label" })
            @Html.TextBoxFor(x => x.FirstName, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.LastName, Html.Loc("LastName").ToString(), new { @class = "control-label" })
            @Html.TextBoxFor(x => x.LastName, new { required = "required", @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.Email, Html.Loc("Email").ToString(), new { @class = "control-label" })
            @Html.TextBoxFor(x => x.Email, new { required = "required", type = "email", @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.Phone, Html.Loc("Phone").ToString(), new { @class = "control-label" })
            @Html.TextBoxFor(x => x.Phone, new { required = "required", type = "tel", @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.BirthDate, Html.Loc("Birthdate").ToString(), new { @class = "control-label" })
            @Html.TextBoxFor(x => x.BirthDate, "{0:yyyy-MM-dd}", new { required = "required", type = "date", @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.Street, Html.Loc("Street").ToString(), new { @class = "control-label" })
            @Html.TextBoxFor(x => x.Street, new { required = "required", @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.ZipCode, Html.Loc("ZipCodeAndCity").ToString(), new { @class = "control-label" })
            @Html.TextBoxFor(x => x.ZipCode, new { required = "required", @class = "form-control" }) @Html.TextBoxFor(x => x.City, new { required = "required", @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.Country, Html.Loc("Country").ToString(), new { @class = "control-label" })
            @Html.DropDownListFor(x => x.Country, countries, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.Nationality, Html.Loc("Nationality").ToString(), new { @class = "control-label" })
            @Html.DropDownListFor(x => x.Nationality, nationalities, new { @class = "form-control" })
        </div>

        </text>
    }
</div>

ePunkt.Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @using (Html.SwitchLocSource("~/Views/Shared/_Layout.cshtml"))
    {
        <title>@(ViewBag.PageTitle ?? Html.Loc("PageTitle"))</title>
    }
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/content/css")
</head>
<body>
    @Html.Partial("GlobalHeader")
    
    @Html.Partial("Header")

    <div class="container">
        @Html.Partial("ContentHeader")
        @RenderBody()
        @Html.Partial("ContentFooter")
    </div>

    @Html.Partial("Footer")

    @Html.Partial("GlobalFooter")

    @Scripts.Render("~/bundles/js")
    @RenderSection("scripts", required: false)
</body>
</html>