ePunkt.Portal/Models/Applicant/IndexViewModel.cs
using ePunkt.Api.Responses;
using System.Collections.Generic;

namespace ePunkt.Portal.Models.Applicant
{
    public class IndexViewModel
    {
        public IndexViewModel(ApplicantResponse applicantResponse, IEnumerable<ApplicantDocumentResponse> documents, IEnumerable<string> jobProfiles, IEnumerable<ApplicantActivityResponse> activities)
        {
            ApplicantResponse = applicantResponse;
            Completeness = new ApplicantCompleteness(applicantResponse, documents, jobProfiles, activities);
        }

        public ApplicantResponse ApplicantResponse { get; set; }
        public ApplicantCompleteness Completeness { get; set; }
    }
}

ePunkt.Portal/Controllers/ApplicantActivitiesController.cs
using ePunkt.Api;
using ePunkt.Api.Client;
using ePunkt.Api.Client.Requests;
using ePunkt.Api.Parameters;
using ePunkt.Api.Responses;
using ePunkt.Portal.Models.ApplicantActivities;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ePunkt.Portal.Controllers
{
    [Authorize]
    public class ApplicantActivitiesController : ControllerBase
    {
        public ApplicantActivitiesController(ApiHttpClient apiClient, CustomSettings settings)
            : base(apiClient, settings)
        {
        }


        public async Task<ActionResult> Index()
        {
            var activities =  await new ApplicantActivitiesGetRequest(GetApplicantId()).LoadResult(ApiClient);
            var viewModel = new IndexViewModel().Fill(activities);
            return View(viewModel);
        }


        public ActionResult Create()
        {
            var viewModel = new EditViewModel().Prepare();
            return View("Edit", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(EditViewModel model)
        {
            if (ModelState.IsValid)
            {
                await new ApplicantActivityPutRequest(GetApplicantId(), new ApplicantActivityParameter
                {
                    Name = model.Name,
                    Start = new FlexDate(model.StartDay, model.StartMonth, model.StartYear),
                    End = new FlexDate(model.EndDay, model.EndMonth, model.EndYear)
                }).LoadResult(ApiClient);
                return RedirectToAction("Index");
            }
            model.Prepare();
            return View("Edit", model);
        }


        public async Task<ActionResult> Edit(int id)
        {
            var activity = await LoadActivity(id);
            if (activity == null)
                return RedirectToAction("Index");
            var viewModel = new EditViewModel().Prepare().Fill(activity);
            return View("Edit", viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, EditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var activity = await LoadActivity(id);
                activity.Name = model.Name;
                activity.Start = new FlexDate(model.StartDay, model.StartMonth, model.StartYear);
                activity.End = new FlexDate(model.EndDay, model.EndMonth, model.EndYear);
                await new ApplicantActivityPostRequest(id, activity).LoadResult(ApiClient);
                return RedirectToAction("Index");
            }
            model.Prepare();
            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id)
        {
            var activity = await LoadActivity(id);
            if (activity != null)
                await new ApplicantActivityDeleteRequest(activity.Id).LoadResult(ApiClient);
            return RedirectToAction("Index");
        }

        private async Task<ApplicantActivityResponse> LoadActivity(int id)
        {
            var activities = await new ApplicantActivitiesGetRequest(GetApplicantId()).LoadResult(ApiClient);
            return activities.FirstOrDefault(x => x.Id == id);
        }
    }
}

ePunkt.Portal/Controllers/ApplicantController.cs
using ePunkt.Api.Client;
using ePunkt.Api.Client.Requests;
using ePunkt.Portal.Models.Applicant;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ePunkt.Portal.Controllers
{
    [Authorize]
    public class ApplicantController : ControllerBase
    {
        public ApplicantController(ApiHttpClient apiClient, CustomSettings settings)
            : base(apiClient, settings)
        {
        }

        public async Task<ActionResult> Index()
        {
            var applicant = await GetApplicant();
            if (applicant == null)
                return RedirectToAction("Logoff", "Account");

            var documents = await new ApplicantDocumentsGetRequest(applicant.Id).LoadResult(ApiClient);
            var jobProfiles = await new ApplicantJobProfilesGetRequest(applicant.Id).LoadResult(ApiClient);
            var activities = await new ApplicantActivitiesGetRequest(applicant.Id).LoadResult(ApiClient);
            return View(new IndexViewModel(applicant, documents, jobProfiles, activities));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(bool? active, bool? newsletter, bool? matchingJobs)
        {
            var applicant = await GetApplicant();
            if (applicant != null)
            {
                if (active.HasValue)
                    applicant.IsActive = active.Value;
                if (newsletter.HasValue)
                    applicant.EnableNewsletter = newsletter.Value;
                if (matchingJobs.HasValue)
                    applicant.EnableMatchingJobsAutoMail = matchingJobs.Value;
                await new ApplicantPostRequest(applicant.Id, applicant).LoadResult(ApiClient);
            }

            return RedirectToAction("Index");
        }
    }
}

ePunkt.Portal/Controllers/ApplicantFilesController.cs
using ePunkt.Api.Client;
using ePunkt.Api.Client.Requests;
using ePunkt.Api.Responses;
using ePunkt.Portal.Models.ApplicantFiles;
using ePunkt.Utilities;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ePunkt.Portal.Controllers
{
    [Authorize]
    public class ApplicantFilesController : ControllerBase
    {
        private readonly UpdateApplicantFileService _updateApplicantFileService;

        public ApplicantFilesController(ApiHttpClient apiClient, CustomSettings settings, UpdateApplicantFileService updateApplicantFileService)
            : base(apiClient, settings)
        {
            _updateApplicantFileService = updateApplicantFileService;
        }

        public async Task<ActionResult> Index()
        {
            var applicant = await GetApplicant();
            if (applicant == null)
                return RedirectToAction("Logoff", "Account");

            var documents = await new ApplicantDocumentsGetRequest(applicant.Id).LoadResult(ApiClient);
            return View(new IndexViewModel(await GetMandator(), documents));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(string type)
        {
            var applicant = await GetApplicant();
            if (applicant != null)
            {
                foreach (var key in Request.Files.AllKeys)
                {
                    var file = Request.Files[key];
                    if (file != null)
                    {

                        if (_updateApplicantFileService.CheckFile(file, type) != UpdateApplicantFileService.CheckFileResult.Ok)
                            if (type.Is("CV"))
                                ModelState.AddModelError("Documents", @"Error-Cv");
                            else if (type.Is("Photo"))
                                ModelState.AddModelError("Documents", @"Error-Photo");
                            else
                                ModelState.AddModelError("Documents", @"Error-Documents");

                        if (!ModelState.IsValid)
                        {
                            var documents = await new ApplicantDocumentsGetRequest(applicant.Id).LoadResult(ApiClient);
                            return View(new IndexViewModel(await GetMandator(), documents));
                        }


                        if (type.Is("CV"))
                            await _updateApplicantFileService.AddCv(ApiClient, applicant, file);
                        else if (type.Is("Photo"))
                            await _updateApplicantFileService.AddPhoto(ApiClient, applicant, file);
                        else
                            await _updateApplicantFileService.AddFile(ApiClient, applicant, file, type);
                    }
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Download(int id)
        {
            var applicant = await GetApplicant();
            if (applicant != null)
            {
                ApplicantDocumentResponse response;
                if (id == -1)
                    response = await new ApplicantCvGetRequest(applicant.Id).LoadResult(ApiClient);
                else if (id == -2)
                    response = await new ApplicantPhotoGetRequest(applicant.Id).LoadResult(ApiClient);
                else
                    response = await new ApplicantDocumentGetRequest(id).LoadResult(ApiClient);

                return new FileContentResult(response.Content, MimeMapping.GetMimeMapping(response.Name + "." + response.FileExtension))
                    {
                        FileDownloadName = response.Name + "." + response.FileExtension
                    };
            }
            return HttpNotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id)
        {
            var applicant = await GetApplicant();
            if (applicant != null)
            {
                if (id == -1)
                    await new ApplicantCvDeleteRequest(applicant.Id).LoadResult(ApiClient);
                else if (id == -2)
                    await new ApplicantPhotoDeleteRequest(applicant.Id).LoadResult(ApiClient);
                else
                    await new ApplicantDocumentDeleteRequest(id).LoadResult(ApiClient);
            }
            return RedirectToAction("Index");
        }
    }
}

ePunkt.Portal/Controllers/ApplicantJobProfilesController.cs
using ePunkt.Api.Client;
using ePunkt.Api.Client.Requests;
using ePunkt.Portal.Models.ApplicantJobProfiles;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ePunkt.Portal.Controllers
{
    [Authorize]
    public class ApplicantJobProfilesController : ControllerBase
    {

        public ApplicantJobProfilesController(ApiHttpClient apiClient, CustomSettings settings)
            : base(apiClient, settings)
        {
        }


        public async Task<ActionResult> Index()
        {
            var jobProfiles = await new ApplicantJobProfilesGetRequest(GetApplicantId()).LoadResult(ApiClient);
            var viewModel = new IndexViewModel().Fill(await GetMandator(), jobProfiles);
            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(IndexViewModel model)
        {
            if (ModelState.IsValid)
                await new ApplicantJobProfilePutRequest(GetApplicantId(), model.SelectedJobProfile).LoadResult(ApiClient);
            return RedirectToAction("Index");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(string name)
        {
            if (ModelState.IsValid)
                await new ApplicantJobProfileDeleteRequest(GetApplicantId(), name).LoadResult(ApiClient);
            return RedirectToAction("Index");
        }
    }
}

ePunkt.Portal/Controllers/ApplicantPersonalInformationController.cs
using ePunkt.Api.Client;
using ePunkt.Portal.Models.ApplicantPersonalInformation;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ePunkt.Portal.Controllers
{
    [Authorize]
    public class ApplicantPersonalInformationController : ControllerBase
    {
        private readonly UpdateApplicantService _updateApplicantService;

        public ApplicantPersonalInformationController(ApiHttpClient apiClient, CustomSettings settings, UpdateApplicantService updateApplicantService)
            : base(apiClient, settings)
        {
            _updateApplicantService = updateApplicantService;
        }

        public async Task<ActionResult> Index()
        {
            var applicant = await GetApplicant();
            if (applicant == null)
                return RedirectToAction("Logoff", "Account");

            var model = new IndexViewModel();
            model.Prepare(await GetMandator(), applicant);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(IndexViewModel model)
        {
            var applicant = await GetApplicant();
            if (applicant == null)
                return RedirectToAction("Logoff", "Account");

            if (ModelState.IsValid)
                applicant = await _updateApplicantService.UpdatePersonalInformation(ApiClient, applicant, model);

            model.Prepare(await GetMandator(), applicant);
            return View(model);
        }

    }
}

ePunkt.Portal/Views/Applicant/Index.cshtml
@model ePunkt.Portal.Models.Applicant.IndexViewModel

<div class="applicantPage">
    <h1>@Html.Loc("Title")</h1>
    <p>@Html.Loc("Description1")</p>

    <div class="applicantCompleteness">
        <div class="row @(Model.Completeness.PersonalInformation >= 100 ? "text-warning" : "text-success")">
            <div class="col-sm-6">
                @Html.ActionLink(Html.Loc("PersonalInformation").ToString(), "Index", "ApplicantPersonalInformation", null, new { @class = "btn btn-sm " + (Model.Completeness.PersonalInformation >= 100 ? "btn-default" : "btn-warning") })
            </div>
            <div class="col-sm-6">
                @Html.Loc("Placeholder_Percent_Complete", Model.Completeness.PersonalInformation)
            </div>
        </div>

        <div class="row @(Model.Completeness.Files >= 100 ? "text-warning" : "text-success")">
            <div class="col-sm-6">
                @Html.ActionLink(Html.Loc("Files").ToString(), "Index", "ApplicantFiles", null, new { @class = "btn btn-sm " + (Model.Completeness.Files >= 100 ? "btn-default" : "btn-warning") })
            </div>
            <div class="col-sm-6">
                @Html.Loc("Placeholder_Percent_Complete", Model.Completeness.Files)
            </div>
        </div>

        <div class="row @(Model.Completeness.JobProfiles >= 100 ? "text-warning" : "text-success")">
            <div class="col-sm-6">
                @Html.ActionLink(Html.Loc("JobProfiles").ToString(), "Index", "ApplicantJobProfiles", null, new { @class = "btn btn-sm " + (Model.Completeness.JobProfiles >= 100 ? "btn-default" : "btn-warning") })
            </div>
            <div class="col-sm-6">
                @Html.Loc("Placeholder_Percent_Complete", Model.Completeness.JobProfiles)
            </div>
        </div>

        <div class="row @(Model.Completeness.Activities >= 100 ? "text-warning" : "text-success")">
            <div class="col-sm-6">
                @Html.ActionLink(Html.Loc("Activities").ToString(), "Index", "ApplicantActivities", null, new { @class = "btn btn-sm " + (Model.Completeness.Activities >= 100 ? "btn-default" : "btn-warning") })
            </div>
            <div class="col-sm-6">
                @Html.Loc("Placeholder_Percent_Complete", Model.Completeness.Activities)
            </div>
        </div>
    </div>

    <p>@Html.Loc("Description2")</p>

    <form method="POST" action="@Url.Action("Index")" role="form">
        @Html.AntiForgeryToken()

        <div class="checkbox">
            <label>
                @Html.CheckBox("active", Model.ApplicantResponse.IsActive)
                @Html.Loc("Active_Label")
            </label>
            <span class="help-block">@Html.Loc("Active_Description", new { @class = "control-label" })</span>
        </div>

        <div class="checkbox">
            <label>
                @Html.CheckBox("matchingJobs", Model.ApplicantResponse.EnableMatchingJobsAutoMail)
                @Html.Loc("MatchingJobs_Label")
            </label>
            <span class="help-block">@Html.Loc("MatchingJobs_Description")</span>
        </div>

        <div class="checkbox">
            <label>
                @Html.CheckBox("newsletter", Model.ApplicantResponse.EnableNewsletter)
                @Html.Loc("Newsletter_Label")
            </label>
            <span class="help-block">@Html.Loc("Newsletter_Description")</span>
        </div>

        <button type="submit" class="btn btn-primary">@Html.Loc("Save")</button>
    </form>

    <p>@Html.Loc("Description3")</p>
</div>